runtime: python311

# Environment variables will be set via gcloud command or .env.yaml
env_variables:
  FLASK_ENV: production
  PYTHONPATH: /srv

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# URL handlers
handlers:
- url: /static
  static_dir: static
  secure: always
  expiration: 1d

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

- url: /.*
  script: auto
  secure: always

# Files to skip during deployment
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests$
- ^(.*/)?test$
- ^Makefile$
- ^README\..*$
- \.gitignore
- ^\.git/.*$
- \.*\.md$
- ^docker.*$
- ^Dockerfile$
- ^requirements-gcp\.txt$
- ^setup_.*\.sh$
- ^.*_guide\.md$