# Cloud Build configuration for Resume Match AI
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/resume-match-ai:$COMMIT_SHA', '.']
  
  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/resume-match-ai:$COMMIT_SHA']
  
  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/resume-match-ai:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/resume-match-ai:latest']
  
  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/resume-match-ai:latest']

# Cloud Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: ALLOW_LOOSE

# Build timeout
timeout: '1800s'

# Images to push to registry
images:
  - 'gcr.io/$PROJECT_ID/resume-match-ai:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/resume-match-ai:latest'

# Substitutions
substitutions:
  _SERVICE_NAME: resume-match-ai
  _REGION: us-central1