steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fit2hire:$BUILD_ID', '.']
    timeout: '600s'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fit2hire:$BUILD_ID']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'fit2hire'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fit2hire:$BUILD_ID'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'FLASK_ENV=production'

# Store the built image
images:
  - 'gcr.io/$PROJECT_ID/fit2hire:$BUILD_ID'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Timeout for the entire build
timeout: '1200s'