steps:
  # Install Python dependencies
  - name: 'python:3.11'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements-gcp.txt']
  
  # Download spaCy model
  - name: 'python:3.11'
    entrypoint: 'python'
    args: ['-m', 'spacy', 'download', 'en_core_web_sm']

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

timeout: '1200s'